/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRegisterPeriodRouteImport } from './routes/home/register-period'
import { Route as HomeHistoryRouteImport } from './routes/home/history'
import { Route as HomeSettingsIndexRouteImport } from './routes/home/settings/index'
import { Route as HomeCurrentPeriodIndexRouteImport } from './routes/home/current-period/index'
import { Route as HomeSettingsChangePasswordRouteImport } from './routes/home/settings/change-password'
import { Route as HomeCurrentPeriodCourseInstanceIndexRouteImport } from './routes/home/current-period/course-instance/index'
import { Route as HomeCurrentPeriodCourseInstanceCourseInstanceIdRouteImport } from './routes/home/current-period/course-instance/$courseInstanceId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRegisterPeriodRoute = HomeRegisterPeriodRouteImport.update({
  id: '/register-period',
  path: '/register-period',
  getParentRoute: () => HomeRoute,
} as any)
const HomeHistoryRoute = HomeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSettingsIndexRoute = HomeSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCurrentPeriodIndexRoute = HomeCurrentPeriodIndexRouteImport.update({
  id: '/current-period/',
  path: '/current-period/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSettingsChangePasswordRoute =
  HomeSettingsChangePasswordRouteImport.update({
    id: '/settings/change-password',
    path: '/settings/change-password',
    getParentRoute: () => HomeRoute,
  } as any)
const HomeCurrentPeriodCourseInstanceIndexRoute =
  HomeCurrentPeriodCourseInstanceIndexRouteImport.update({
    id: '/current-period/course-instance/',
    path: '/current-period/course-instance/',
    getParentRoute: () => HomeRoute,
  } as any)
const HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute =
  HomeCurrentPeriodCourseInstanceCourseInstanceIdRouteImport.update({
    id: '/current-period/course-instance/$courseInstanceId',
    path: '/current-period/course-instance/$courseInstanceId',
    getParentRoute: () => HomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/register-period': typeof HomeRegisterPeriodRoute
  '/home/settings/change-password': typeof HomeSettingsChangePasswordRoute
  '/home/current-period/': typeof HomeCurrentPeriodIndexRoute
  '/home/settings/': typeof HomeSettingsIndexRoute
  '/home/current-period/course-instance/$courseInstanceId': typeof HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute
  '/home/current-period/course-instance/': typeof HomeCurrentPeriodCourseInstanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/register-period': typeof HomeRegisterPeriodRoute
  '/home/settings/change-password': typeof HomeSettingsChangePasswordRoute
  '/home/current-period': typeof HomeCurrentPeriodIndexRoute
  '/home/settings': typeof HomeSettingsIndexRoute
  '/home/current-period/course-instance/$courseInstanceId': typeof HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute
  '/home/current-period/course-instance': typeof HomeCurrentPeriodCourseInstanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/register-period': typeof HomeRegisterPeriodRoute
  '/home/settings/change-password': typeof HomeSettingsChangePasswordRoute
  '/home/current-period/': typeof HomeCurrentPeriodIndexRoute
  '/home/settings/': typeof HomeSettingsIndexRoute
  '/home/current-period/course-instance/$courseInstanceId': typeof HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute
  '/home/current-period/course-instance/': typeof HomeCurrentPeriodCourseInstanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/home'
    | '/login'
    | '/register'
    | '/home/history'
    | '/home/register-period'
    | '/home/settings/change-password'
    | '/home/current-period/'
    | '/home/settings/'
    | '/home/current-period/course-instance/$courseInstanceId'
    | '/home/current-period/course-instance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/home'
    | '/login'
    | '/register'
    | '/home/history'
    | '/home/register-period'
    | '/home/settings/change-password'
    | '/home/current-period'
    | '/home/settings'
    | '/home/current-period/course-instance/$courseInstanceId'
    | '/home/current-period/course-instance'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/home'
    | '/login'
    | '/register'
    | '/home/history'
    | '/home/register-period'
    | '/home/settings/change-password'
    | '/home/current-period/'
    | '/home/settings/'
    | '/home/current-period/course-instance/$courseInstanceId'
    | '/home/current-period/course-instance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  HomeRoute: typeof HomeRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/register-period': {
      id: '/home/register-period'
      path: '/register-period'
      fullPath: '/home/register-period'
      preLoaderRoute: typeof HomeRegisterPeriodRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/history': {
      id: '/home/history'
      path: '/history'
      fullPath: '/home/history'
      preLoaderRoute: typeof HomeHistoryRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/settings/': {
      id: '/home/settings/'
      path: '/settings'
      fullPath: '/home/settings/'
      preLoaderRoute: typeof HomeSettingsIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/current-period/': {
      id: '/home/current-period/'
      path: '/current-period'
      fullPath: '/home/current-period/'
      preLoaderRoute: typeof HomeCurrentPeriodIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/settings/change-password': {
      id: '/home/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/home/settings/change-password'
      preLoaderRoute: typeof HomeSettingsChangePasswordRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/current-period/course-instance/': {
      id: '/home/current-period/course-instance/'
      path: '/current-period/course-instance'
      fullPath: '/home/current-period/course-instance/'
      preLoaderRoute: typeof HomeCurrentPeriodCourseInstanceIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/current-period/course-instance/$courseInstanceId': {
      id: '/home/current-period/course-instance/$courseInstanceId'
      path: '/current-period/course-instance/$courseInstanceId'
      fullPath: '/home/current-period/course-instance/$courseInstanceId'
      preLoaderRoute: typeof HomeCurrentPeriodCourseInstanceCourseInstanceIdRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeHistoryRoute: typeof HomeHistoryRoute
  HomeRegisterPeriodRoute: typeof HomeRegisterPeriodRoute
  HomeSettingsChangePasswordRoute: typeof HomeSettingsChangePasswordRoute
  HomeCurrentPeriodIndexRoute: typeof HomeCurrentPeriodIndexRoute
  HomeSettingsIndexRoute: typeof HomeSettingsIndexRoute
  HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute: typeof HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute
  HomeCurrentPeriodCourseInstanceIndexRoute: typeof HomeCurrentPeriodCourseInstanceIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeHistoryRoute: HomeHistoryRoute,
  HomeRegisterPeriodRoute: HomeRegisterPeriodRoute,
  HomeSettingsChangePasswordRoute: HomeSettingsChangePasswordRoute,
  HomeCurrentPeriodIndexRoute: HomeCurrentPeriodIndexRoute,
  HomeSettingsIndexRoute: HomeSettingsIndexRoute,
  HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute:
    HomeCurrentPeriodCourseInstanceCourseInstanceIdRoute,
  HomeCurrentPeriodCourseInstanceIndexRoute:
    HomeCurrentPeriodCourseInstanceIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  HomeRoute: HomeRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
