/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeRegisterPeriodRouteImport } from './routes/home/register-period'
import { Route as HomeHistoryRouteImport } from './routes/home/history'
import { Route as HomeSettingsIndexRouteImport } from './routes/home/settings/index'
import { Route as HomeCurrentPeriodIndexRouteImport } from './routes/home/current-period/index'
import { Route as HomeCourseInstanceIndexRouteImport } from './routes/home/course-instance/index'
import { Route as HomeSettingsChangePasswordRouteImport } from './routes/home/settings/change-password'
import { Route as HomeCourseInstanceCourseInstanceIdRouteImport } from './routes/home/course-instance/$courseInstanceId'
import { Route as HomeCurrentPeriodCourseInstanceIndexRouteImport } from './routes/home/current-period/course-instance/index'
import { Route as HomeCourseInstanceEditCourseInstanceIdRouteImport } from './routes/home/course-instance/edit.$courseInstanceId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeRegisterPeriodRoute = HomeRegisterPeriodRouteImport.update({
  id: '/register-period',
  path: '/register-period',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHistoryRoute = HomeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsIndexRoute = HomeSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCurrentPeriodIndexRoute = HomeCurrentPeriodIndexRouteImport.update({
  id: '/current-period/',
  path: '/current-period/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCourseInstanceIndexRoute = HomeCourseInstanceIndexRouteImport.update({
  id: '/course-instance/',
  path: '/course-instance/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsChangePasswordRoute =
  HomeSettingsChangePasswordRouteImport.update({
    id: '/settings/change-password',
    path: '/settings/change-password',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeCourseInstanceCourseInstanceIdRoute =
  HomeCourseInstanceCourseInstanceIdRouteImport.update({
    id: '/course-instance/$courseInstanceId',
    path: '/course-instance/$courseInstanceId',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeCurrentPeriodCourseInstanceIndexRoute =
  HomeCurrentPeriodCourseInstanceIndexRouteImport.update({
    id: '/current-period/course-instance/',
    path: '/current-period/course-instance/',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeCourseInstanceEditCourseInstanceIdRoute =
  HomeCourseInstanceEditCourseInstanceIdRouteImport.update({
    id: '/course-instance/edit/$courseInstanceId',
    path: '/course-instance/edit/$courseInstanceId',
    getParentRoute: () => HomeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/register-period': typeof HomeRegisterPeriodRoute
  '/home/': typeof HomeIndexRoute
  '/home/course-instance/$courseInstanceId': typeof HomeCourseInstanceCourseInstanceIdRoute
  '/home/settings/change-password': typeof HomeSettingsChangePasswordRoute
  '/home/course-instance/': typeof HomeCourseInstanceIndexRoute
  '/home/current-period/': typeof HomeCurrentPeriodIndexRoute
  '/home/settings/': typeof HomeSettingsIndexRoute
  '/home/course-instance/edit/$courseInstanceId': typeof HomeCourseInstanceEditCourseInstanceIdRoute
  '/home/current-period/course-instance/': typeof HomeCurrentPeriodCourseInstanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/register-period': typeof HomeRegisterPeriodRoute
  '/home': typeof HomeIndexRoute
  '/home/course-instance/$courseInstanceId': typeof HomeCourseInstanceCourseInstanceIdRoute
  '/home/settings/change-password': typeof HomeSettingsChangePasswordRoute
  '/home/course-instance': typeof HomeCourseInstanceIndexRoute
  '/home/current-period': typeof HomeCurrentPeriodIndexRoute
  '/home/settings': typeof HomeSettingsIndexRoute
  '/home/course-instance/edit/$courseInstanceId': typeof HomeCourseInstanceEditCourseInstanceIdRoute
  '/home/current-period/course-instance': typeof HomeCurrentPeriodCourseInstanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/register-period': typeof HomeRegisterPeriodRoute
  '/home/': typeof HomeIndexRoute
  '/home/course-instance/$courseInstanceId': typeof HomeCourseInstanceCourseInstanceIdRoute
  '/home/settings/change-password': typeof HomeSettingsChangePasswordRoute
  '/home/course-instance/': typeof HomeCourseInstanceIndexRoute
  '/home/current-period/': typeof HomeCurrentPeriodIndexRoute
  '/home/settings/': typeof HomeSettingsIndexRoute
  '/home/course-instance/edit/$courseInstanceId': typeof HomeCourseInstanceEditCourseInstanceIdRoute
  '/home/current-period/course-instance/': typeof HomeCurrentPeriodCourseInstanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/demo'
    | '/login'
    | '/register'
    | '/home/history'
    | '/home/register-period'
    | '/home/'
    | '/home/course-instance/$courseInstanceId'
    | '/home/settings/change-password'
    | '/home/course-instance/'
    | '/home/current-period/'
    | '/home/settings/'
    | '/home/course-instance/edit/$courseInstanceId'
    | '/home/current-period/course-instance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/home/history'
    | '/home/register-period'
    | '/home'
    | '/home/course-instance/$courseInstanceId'
    | '/home/settings/change-password'
    | '/home/course-instance'
    | '/home/current-period'
    | '/home/settings'
    | '/home/course-instance/edit/$courseInstanceId'
    | '/home/current-period/course-instance'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/demo'
    | '/login'
    | '/register'
    | '/home/history'
    | '/home/register-period'
    | '/home/'
    | '/home/course-instance/$courseInstanceId'
    | '/home/settings/change-password'
    | '/home/course-instance/'
    | '/home/current-period/'
    | '/home/settings/'
    | '/home/course-instance/edit/$courseInstanceId'
    | '/home/current-period/course-instance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/register-period': {
      id: '/home/register-period'
      path: '/register-period'
      fullPath: '/home/register-period'
      preLoaderRoute: typeof HomeRegisterPeriodRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/history': {
      id: '/home/history'
      path: '/history'
      fullPath: '/home/history'
      preLoaderRoute: typeof HomeHistoryRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/settings/': {
      id: '/home/settings/'
      path: '/settings'
      fullPath: '/home/settings/'
      preLoaderRoute: typeof HomeSettingsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/current-period/': {
      id: '/home/current-period/'
      path: '/current-period'
      fullPath: '/home/current-period/'
      preLoaderRoute: typeof HomeCurrentPeriodIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/course-instance/': {
      id: '/home/course-instance/'
      path: '/course-instance'
      fullPath: '/home/course-instance/'
      preLoaderRoute: typeof HomeCourseInstanceIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/settings/change-password': {
      id: '/home/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/home/settings/change-password'
      preLoaderRoute: typeof HomeSettingsChangePasswordRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/course-instance/$courseInstanceId': {
      id: '/home/course-instance/$courseInstanceId'
      path: '/course-instance/$courseInstanceId'
      fullPath: '/home/course-instance/$courseInstanceId'
      preLoaderRoute: typeof HomeCourseInstanceCourseInstanceIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/current-period/course-instance/': {
      id: '/home/current-period/course-instance/'
      path: '/current-period/course-instance'
      fullPath: '/home/current-period/course-instance/'
      preLoaderRoute: typeof HomeCurrentPeriodCourseInstanceIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/course-instance/edit/$courseInstanceId': {
      id: '/home/course-instance/edit/$courseInstanceId'
      path: '/course-instance/edit/$courseInstanceId'
      fullPath: '/home/course-instance/edit/$courseInstanceId'
      preLoaderRoute: typeof HomeCourseInstanceEditCourseInstanceIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeHistoryRoute: typeof HomeHistoryRoute
  HomeRegisterPeriodRoute: typeof HomeRegisterPeriodRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeCourseInstanceCourseInstanceIdRoute: typeof HomeCourseInstanceCourseInstanceIdRoute
  HomeSettingsChangePasswordRoute: typeof HomeSettingsChangePasswordRoute
  HomeCourseInstanceIndexRoute: typeof HomeCourseInstanceIndexRoute
  HomeCurrentPeriodIndexRoute: typeof HomeCurrentPeriodIndexRoute
  HomeSettingsIndexRoute: typeof HomeSettingsIndexRoute
  HomeCourseInstanceEditCourseInstanceIdRoute: typeof HomeCourseInstanceEditCourseInstanceIdRoute
  HomeCurrentPeriodCourseInstanceIndexRoute: typeof HomeCurrentPeriodCourseInstanceIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeHistoryRoute: HomeHistoryRoute,
  HomeRegisterPeriodRoute: HomeRegisterPeriodRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeCourseInstanceCourseInstanceIdRoute:
    HomeCourseInstanceCourseInstanceIdRoute,
  HomeSettingsChangePasswordRoute: HomeSettingsChangePasswordRoute,
  HomeCourseInstanceIndexRoute: HomeCourseInstanceIndexRoute,
  HomeCurrentPeriodIndexRoute: HomeCurrentPeriodIndexRoute,
  HomeSettingsIndexRoute: HomeSettingsIndexRoute,
  HomeCourseInstanceEditCourseInstanceIdRoute:
    HomeCourseInstanceEditCourseInstanceIdRoute,
  HomeCurrentPeriodCourseInstanceIndexRoute:
    HomeCurrentPeriodCourseInstanceIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
